In [2]:
import pandas as pd

In [3]:
df_2021 = pd.read_parquet("../parquet/dsei-2021")
df_2019 = pd.read_parquet("../parquet/dsei-2019")
df_2017 = pd.read_parquet("../parquet/dsei-2017")
df_2015 = pd.read_parquet("../parquet/dsei-2015")
df_2013 = pd.read_parquet("../parquet/dsei-2013")
df_2011 = pd.read_parquet("../parquet/dsei-2011")
df_2009 = pd.read_parquet("../parquet/dsei-2009")
df_2007 = pd.read_parquet("../parquet/dsei-2007")
df_2005 = pd.read_parquet("../parquet/dsei-2005")
df_2003 = pd.read_parquet("../parquet/dsei-2003")
df_2001 = pd.read_parquet("../parquet/dsei-2001")
df_1999 = pd.read_parquet("../parquet/dsei-1999")

In [4]:
df_2021

,address_iso2,address_text,address_lat,name,country_iso2,exhibitorUrl,address_lon,country_text
0,GB,Chetwynd Bks\nChilwell\nNottingham\nNG9 5HA\nU...,52.91241090000000,170 (Infra Sp) Engineering Group,None,https://www.dsei.co.uk/exhibitors/170-infra-sp...,-1.24352950000000000,None
1,None,None,None,2 Excel Aviation,GB,https://www.dsei.co.uk/exhibitors/2excel-aviation,None,United Kingdom
2,US,River Front Services\n15049 Conference Center ...,38.88041000000000,21st Century Breaching Kit,None,https://www.dsei.co.uk/exhibitors/21st-century...,-77.45601700000000000,None
3,None,None,None,360iSR,GB,https://www.dsei.co.uk/exhibitors/360isr,None,United Kingdom
4,None,None,None,3M,SE,https://www.dsei.co.uk/exhibitors/3m,None,Sweden
...,...,...,...,...,...,...,...,...
1605,GB,iTrinegy\nBusiness and Technology Centre\nBess...,51.90178740000000,iTrinegy,None,https://www.dsei.co.uk/exhibitors/itrinegy,-0.21586950000000000,None
1606,GB,7 East Street\nTHAME\nOxfordshire\nOX9 3JS\nUn...,51.74521090000000,kc4business Ltd,None,https://www.dsei.co.uk/exhibitors/kc4business-ltd,-0.97315999999999990,None
1607,None,None,None,maxon,GB,https://www.dsei.co.uk/exhibitors/maxon,None,United Kingdom
1608,CH,Güterstrasse 20\nDäniken\n4658\nSwitzerland,47.36121630000000,saltech AG,None,https://www.dsei.co.uk/exhibitors/saltech-ag,7.97763210000000000,None
1609,DE,Werftstrasse 112-114\nKiel\n24143\nGermany,54.31666560000000,thyssenkrupp,None,https://www.dsei.co.uk/exhibitors/thyssenkrupp...,10.15144700000000000,None

In [5]:
df = pd.concat([df_2021, df_2019, df_2017, df_2015, df_2013, df_2011, df_2009, df_2007, df_2005, df_2003, df_2001, df_1999], axis=1)

In [6]:
df

,address_iso2,address_text,address_lat,name,country_iso2,exhibitorUrl,address_lon,country_text,address_iso2,website,...,name,country_iso2,country_text,name,country_iso2,country_text,name,country_iso2,country_text,name
0,GB,Chetwynd Bks\nChilwell\nNottingham\nNG9 5HA\nU...,52.91241090000000,170 (Infra Sp) Engineering Group,None,https://www.dsei.co.uk/exhibitors/170-infra-sp...,-1.24352950000000000,None,None,None,...,3e Technologies,US,USA,AB Connectors (Northampton) Ltd,GB,UK,4H Jena Engineering GmbH,DE,Germany,A1 Solutions
1,None,None,None,2 Excel Aviation,GB,https://www.dsei.co.uk/exhibitors/2excel-aviation,None,United Kingdom,US,https://14bis.aero,...,3M (UK),GB,UK,AB Precision (Poole) Ltd,GB,UK,AB Connectors (Northampton) Ltd,GB,UK,Aardvark Clear Mine Ltd
2,US,River Front Services\n15049 Conference Center ...,38.88041000000000,21st Century Breaching Kit,None,https://www.dsei.co.uk/exhibitors/21st-century...,-77.45601700000000000,None,GB,http://army.mod.uk,...,3-Way Networks,GB,UK,ABRO (Army Base Repair Organisation),GB,UK,AB Precision (Poole) Ltd,GB,UK,Aarhus Flydedok A/S
3,None,None,None,360iSR,GB,https://www.dsei.co.uk/exhibitors/360isr,None,United Kingdom,None,None,...,911EP,US,USA,ACRA Control Ltd,IE,Rep. Ireland,ABRO (Army Base Repair Organisation),GB,UK,AB Precision (Poole)
4,None,None,None,3M,SE,https://www.dsei.co.uk/exhibitors/3m,None,Sweden,None,None,...,AAI Corporation,US,USA,ADA Composite Armour,AU,Australia,ABSL Power Solutions Ltd,GB,UK,ABRO - Army Base Repair Organisation
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4379,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4380,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DE,https://www.zoll.com/military,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4381,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4382,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4383,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GB,http://www.zuken.com,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
import leafmap
import geopandas

m = leafmap.Map()

map_2021 = df_2021.astype({'address_lon': float, 'address_lat': float})

gdf = geopandas.GeoDataFrame(map_2021, geometry=geopandas.points_from_xy(map_2021.address_lon, map_2021.address_lat))
gdf.crs="EPSG:4326"
m.add_gdf(gdf, layer_name="DSEI 2021 Exhibitors", info_mode='on_click')
m.zoom_to_bounds((-10, 49, 2, 60))
m

Map(center=[20, 0], controls=(ZoomControl(options=['position', 'zoom_in_text', 'zoom_in_title', 'zoom_out_text…